added new tests
Pavellys/MoiShopBY pull request #1
Opened 2021-03-04 16:20 UTC by Pavellys

2021-03-04 21:01 UTC, vchesnakoutest requested changes
Please make fixes

2021-03-04 21:01 UTC, vchesnakoutest commented on src/main/java/constants/Constants.java
> +    By BUTTON_ENTER = By.xpath("//*[contains(text(),'Войти')]");
все локаторы давай описывать в классах со страницами. и добавляй MY_ACCOUNT_XPATH, ENTER_BUTTON_XPATH и тд

2021-03-04 21:01 UTC, vchesnakoutest commented on src/main/java/pages/HeadMenuModal.java
> +    WebElement catalog;
пиши конкретно, это ссылка или кнопка и тд.

catalogLink or catalogButton

2021-03-04 21:01 UTC, vchesnakoutest commented on src/main/java/pages/HeadMenuModal.java
> +    WebElement brands;
пиши конкретно, это ссылка или кнопка и тд.

2021-03-04 21:01 UTC, vchesnakoutest commented on src/main/java/pages/HeadMenuModal.java
> +    WebElement search;
пиши конкретно, это ссылка или кнопка и тд.

2021-03-04 21:01 UTC, vchesnakoutest commented on src/main/java/pages/HeadMenuModal.java
> +    WebElement buttonCart;
пиши конкретно, это ссылка или кнопка и тд.

2021-03-04 21:01 UTC, vchesnakoutest commented on src/main/java/pages/HeadMenuModal.java
> +    public HeadMenuModal clickToElementMenu(String nameSection){
clickOnMenuElement

2021-03-04 21:01 UTC, vchesnakoutest commented on src/main/java/pages/HeadMenuModal.java
> +    public HeadMenuModal checkingCatalog(){
поправь имя метода, будь конкретнее, что он делает
clickOnCatalogButton or link

2021-03-04 21:01 UTC, vchesnakoutest commented on src/main/java/pages/HeadMenuModal.java
> +    public HeadMenuModal checkingBrands(){
поправь имя метода, будь конкретнее, что он делает

2021-03-04 21:01 UTC, vchesnakoutest commented on src/main/java/pages/HeadMenuModal.java
> +    public HeadMenuModal checkingSearch(){
поправь имя метода, будь конкретнее, что он делает

2021-03-04 21:01 UTC, vchesnakoutest commented on src/main/java/pages/HeadMenuModal.java
> +    public HeadMenuModal checkingMyAccount(){
поправь имя метода, будь конекретнее, что он делает

2021-03-04 21:01 UTC, vchesnakoutest commented on src/main/java/pages/HeadMenuModal.java
> +    public HeadMenuModal checkingButtonCart(){
поправь имя метода, будь конекретнее, что он делает

2021-03-04 21:01 UTC, vchesnakoutest commented on src/main/java/pages/HeadMenuModal.java
> +    public boolean catalogIsDisplayed(){
isCatalogDisplayed

2021-03-04 21:01 UTC, vchesnakoutest commented on src/main/java/pages/HeadMenuModal.java
> +    public boolean brandsIsDisplayed(){
is в начале

2021-03-04 21:01 UTC, vchesnakoutest commented on src/main/java/pages/HeadMenuModal.java
> +    public boolean searchIsDisplayed(){
is в начале

2021-03-04 21:01 UTC, vchesnakoutest commented on src/main/java/pages/HeadMenuModal.java
> +    private static final String MENU_SECTION = "//*[contains(text(),'%s')]";
MENU_SECTION_XPATH

2021-03-04 21:01 UTC, vchesnakoutest commented on src/main/java/pages/HeadMenuModal.java
> +    private static final By CATALOG_IS_DISPLAYED = By.id("ctgr");
укажи явно , что это за элементы. IS_DISPLAYED писать не надо

2021-03-05 06:34 UTC, Pavellys commented on src/main/java/constants/Constants.java
> +    By BUTTON_ENTER = By.xpath("//*[contains(text(),'Войти')]");
done

2021-03-05 06:34 UTC, Pavellys commented on src/main/java/pages/HeadMenuModal.java
> +    WebElement catalog;
done

2021-03-05 06:36 UTC, Pavellys commented on src/main/java/pages/HeadMenuModal.java
> +    WebElement brands;
done

2021-03-05 06:36 UTC, Pavellys commented on src/main/java/pages/HeadMenuModal.java
> +    WebElement search;
done

2021-03-05 06:36 UTC, Pavellys commented on src/main/java/pages/HeadMenuModal.java
> +    WebElement buttonCart;
done

2021-03-05 06:42 UTC, Pavellys commented on src/main/java/pages/HeadMenuModal.java
> +    public boolean catalogIsDisplayed(){
done

2021-03-05 06:42 UTC, Pavellys commented on src/main/java/pages/HeadMenuModal.java
> +    public boolean brandsIsDisplayed(){
done

2021-03-05 06:42 UTC, Pavellys commented on src/main/java/pages/HeadMenuModal.java
> +    public boolean searchIsDisplayed(){
done

2021-03-05 06:42 UTC, Pavellys commented on src/main/java/pages/HeadMenuModal.java
> +    private static final String MENU_SECTION = "//*[contains(text(),'%s')]";
done

2021-03-05 06:42 UTC, Pavellys commented on src/main/java/pages/HeadMenuModal.java
> +    private static final By CATALOG_IS_DISPLAYED = By.id("ctgr");
done

2021-03-07 12:22 UTC, merged