added hard test
Pavellys/MoiShopBY pull request #2
Opened 2021-03-07 12:23 UTC by Pavellys

2021-03-07 14:36 UTC, vchesnakoutest requested changes
please make fixes

2021-03-07 14:36 UTC, vchesnakoutest commented on src/main/java/objects/AddressUser.java
> +    }
можно удалить этот метод полностью и поставить Lombok аннотацию @AllArgsConstructor над объявлением класса

2021-03-07 14:36 UTC, vchesnakoutest commented on src/main/java/objects/UserData.java
> +    }
можно удалить этот метод полностью и поставить Lombok аннотацию @AllArgsConstructor над объявлением класса

2021-03-07 14:36 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    @FindBy(xpath = "//*[@class=\"btn btn-moi add-to-cart\"]")
используй одинарные кавычки в xpath локаторах:
//*[@class='btn btn-moi add-to-cart']

также в локаторе class состоит из нескольких классов, лучше писать так:
//*[contains(@class, 'add-to-cart')] - проверь работает ли

2021-03-07 14:36 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    @FindBy(xpath = "//*[@class='ajs-message ajs-addtocart ajs-visible']")
тут тоже самое

2021-03-07 14:36 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    public CartPage clickToProduct(String productName){
clickOnProduct

2021-03-07 14:36 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    public CartPage clickToButtonInCart() {
clickOnButtonInCart

2021-03-07 14:36 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    WebElement popUp;
тут в имени лучше уточняй, какой именно popup. Например: cartPopup и тд

2021-03-07 14:36 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    public CartPage isPopUpDisplayed(){
waitForCart(или какой там попап)PopUpDisplayed

2021-03-07 14:36 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    public boolean checkInCart(String productInCart){
boolean методы должны в названии начинаться на 'is': isProductAddedToCart или как-то так

2021-03-07 14:36 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    public CartPage clickToCheckoutButton(){
clickOnCheckoutButton

2021-03-07 14:36 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    public CartPage clickCatalog(){
clickCatalogButton

2021-03-07 14:36 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    public CartPage inputUserData(UserData userData){
inputUserDataInLoginField или как-то так

2021-03-07 14:36 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +        jse.executeScript("arguments[0].scrollIntoView(true);",checkoutButtonEndOrder);
для js давай создадим отдельный пакет utils , в нем класс JavaScriptUtils и в нем статический метод 
```
executeJavaScript(String scriptToExecute, WebElement locator) {
   JavascriptExecutor jse = (JavascriptExecutor)driver;
   jse.executeScript(scriptToExecute, locator);
}
```
соотв тут уже просто будешь вызывать этот метод JavaScriptUtils.executeJavaScript("arguments[0].scrollIntoView(true);", checkoutButtonEndOrder)

и из любого другого класса,  где это будет необходимо

2021-03-07 14:36 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    public CartPage clickCheckboxDeliveryOnRB(){
что такое RB не понятно, лучше расшифровать

2021-03-07 14:36 UTC, vchesnakoutest commented on src/test/java/tests/CartTest.java
> +            "Брестский", "Папанина", "22", "1", "22", "2", "1");
давай вынесем это в интерфейс класс ITestData (надо создать). 

И делай в BaseTest implements ITestData

2021-03-07 14:36 UTC, vchesnakoutest commented on src/test/java/tests/CartTest.java
> +    public void addPromProductInCartTest() {
addProm>>>o<<<ProductInCartTest ?

2021-03-07 14:36 UTC, vchesnakoutest commented on src/test/java/tests/CartTest.java
> +        Assert.assertTrue(cartPage.isCheckoutButtonDisplayed());
а на сайте кнопка Checkout именно появляется ? Или она не активная и становиться активной ?

2021-03-07 18:24 UTC, Pavellys commented on src/test/java/tests/CartTest.java
> +            "Брестский", "Папанина", "22", "1", "22", "2", "1");
готово

2021-03-07 18:25 UTC, Pavellys commented on src/test/java/tests/CartTest.java
> +    public void addPromProductInCartTest() {
не совсем понял что тут требуется ?)

2021-03-07 18:26 UTC, Pavellys commented on src/test/java/tests/CartTest.java
> +        Assert.assertTrue(cartPage.isCheckoutButtonDisplayed());
Я сделал такую проверку что бы не кликакть эту кнопку, так как сайт рабочий и не хотелось бы заказы оформлять)

2021-03-07 18:27 UTC, Pavellys commented on src/main/java/pages/CartPage.java
> +    public CartPage clickCheckboxDeliveryOnRB(){
"Доставка по РБ" так на сайте называется способ доставки

2021-03-07 18:42 UTC, Pavellys commented on src/main/java/pages/CartPage.java
> +        jse.executeScript("arguments[0].scrollIntoView(true);",checkoutButtonEndOrder);
готово

2021-03-07 18:43 UTC, Pavellys commented on src/main/java/pages/CartPage.java
> +    public CartPage clickToProduct(String productName){
готово

2021-03-07 18:50 UTC, Pavellys commented on src/main/java/pages/CartPage.java
> +    @FindBy(xpath = "//*[@class=\"btn btn-moi add-to-cart\"]")
готово

2021-03-07 18:50 UTC, Pavellys commented on src/main/java/pages/CartPage.java
> +    @FindBy(xpath = "//*[@class='ajs-message ajs-addtocart ajs-visible']")
готово

2021-03-07 18:51 UTC, Pavellys commented on src/main/java/objects/UserData.java
> +    }
готово

2021-03-07 18:51 UTC, Pavellys commented on src/main/java/objects/AddressUser.java
> +    }
готово

2021-03-07 20:04 UTC, vchesnakoutest requested changes
please make fixes

2021-03-07 20:04 UTC, vchesnakoutest commented on src/main/java/pages/BasePage.java
> +abstract class BasePage extends JavaScriptUtils {
в JavaScriptUtils мы сделали метод статичным для того, чтобы его можно было вызывать из любого места без создания экземпляра класса. Соотв. тут не надо экстендить этот класс

2021-03-07 20:04 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    @FindBy(xpath = "//*[contains(@Class,'ajs-message')]")
@Class - с маленькой буквы

2021-03-07 20:04 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    WebElement popUp;
не вижу изменений

2021-03-07 20:04 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +        executeJavaScript("arguments[0].scrollIntoView(true);", checkoutButtonEndOrder, driver);
тут будет JavaScriptUtils.executeJavaScript.......

2021-03-07 20:04 UTC, vchesnakoutest commented on src/test/java/tests/BaseTest.java
> +public class BaseTest  implements TestConstants, ITestData {
между BaseTest и implements лишний пробел

2021-03-07 20:04 UTC, vchesnakoutest commented on src/test/java/tests/BaseTest.java
> +public class BaseTest  implements TestConstants, ITestData {
и давай ещё TestConstants переименуем в ITestConstants , т.к это интерфейс

2021-03-07 20:04 UTC, vchesnakoutest commented on src/test/java/tests/CartTest.java
> +        Assert.assertTrue(cartPage.isCheckoutButtonDisplayed());
да я понимаю) спрашиваю потому что, проверка на то, что кнопки не было и она появилась - это одна проверка. А если кнопка была, но она не активная и стала активной - это другая проверка. Соотв. и методы разные используются для того, чтобы это проверить

2021-03-07 20:04 UTC, vchesnakoutest commented on src/test/java/tests_constants/ITestData.java
> +package tests_constants;
давай положим этот класс в отдельный пакет и назовем tests_data или что-то похожее

2021-03-07 20:04 UTC, vchesnakoutest commented on src/test/java/tests/CartTest.java
>  public class CartTest extends BaseTest {
удали не используемые импорты 
import objects.AddressUser;
import objects.UserData;

2021-03-07 20:04 UTC, vchesnakoutest commented on src/test/java/tests/HeadMenuTest.java
между BaseTest и { пробел

2021-03-07 20:04 UTC, vchesnakoutest commented on src/test/java/tests_constants/ITestData.java
> +public interface ITestData {
и давай сделаем это не интерфейсом, а классом все-таки. Интерфейс должен по сути содержать поля, а мы в нем объекты создаем. В тестах, где нужны эти данные просто создавай объект этого класса. И название поменяй на просто TestData

2021-03-07 20:13 UTC, Pavellys commented on src/main/java/pages/BasePage.java
> +abstract class BasePage extends JavaScriptUtils {
готово

2021-03-07 20:13 UTC, Pavellys commented on src/main/java/pages/CartPage.java
> +    @FindBy(xpath = "//*[contains(@Class,'ajs-message')]")
готово

2021-03-07 20:16 UTC, Pavellys commented on src/main/java/pages/CartPage.java
> +        executeJavaScript("arguments[0].scrollIntoView(true);", checkoutButtonEndOrder, driver);
готово

2021-03-07 20:17 UTC, Pavellys commented on src/test/java/tests/BaseTest.java
> +public class BaseTest  implements TestConstants, ITestData {
готово

2021-03-07 20:19 UTC, Pavellys commented on src/test/java/tests_constants/ITestData.java
> +package tests_constants;
готово

2021-03-07 20:21 UTC, Pavellys commented on src/test/java/tests_constants/ITestData.java
> +public interface ITestData {
готово

2021-03-07 20:25 UTC, Pavellys commented on src/test/java/tests/HeadMenuTest.java
done

2021-03-07 20:25 UTC, Pavellys commented on src/test/java/tests/CartTest.java
>  public class CartTest extends BaseTest {
done

2021-03-09 16:12 UTC, Pavellys commented on src/main/java/pages/CartPage.java
> +    public CartPage clickToButtonInCart() {
готово

2021-03-09 16:13 UTC, Pavellys commented on src/main/java/pages/CartPage.java
> +    WebElement popUp;
done

2021-03-09 16:14 UTC, Pavellys commented on src/main/java/pages/CartPage.java
> +    public CartPage isPopUpDisplayed(){
done

2021-03-09 16:15 UTC, Pavellys commented on src/main/java/pages/CartPage.java
> +    public boolean checkInCart(String productInCart){
done

2021-03-09 16:15 UTC, Pavellys commented on src/main/java/pages/CartPage.java
> +    public CartPage clickToCheckoutButton(){
done

2021-03-09 16:16 UTC, Pavellys commented on src/main/java/pages/CartPage.java
> +    public CartPage clickCatalog(){
done

2021-03-09 16:18 UTC, Pavellys commented on src/main/java/pages/CartPage.java
> +    public CartPage inputUserData(UserData userData){
done

2021-03-09 16:19 UTC, merged

2021-03-10 14:36 UTC, vchesnakoutest reviewed
please merge