Circleci project setup
Pavellys/MoiShopBY pull request #7
Opened 2021-03-09 16:35 UTC by Pavellys

added description for Test, @Step, logs, circleCI, allure-report

2021-03-09 18:46 UTC, vchesnakoutest requested changes

2021-03-09 18:46 UTC, vchesnakoutest commented on .circleci/config.yml
> +      #          command: chmod 777 src/test/resources/webdrivers/linux/chromedriver
убрать

2021-03-09 18:46 UTC, vchesnakoutest commented on pom.xml
> +                <version>3.8.0</version>
вынести в properties

2021-03-09 18:46 UTC, vchesnakoutest commented on src/test/java/tests/CartTest.java
> +        Assert.assertTrue(cartPage.isCheckInCart(PROMOTION_PRODUCT));
isProductIsAddedToCart

2021-03-09 18:46 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +        log.info("Entering data in address form 'Доставка по РБ'");
String.format("Entering address: '%s' in address form 'Доставка по РБ'", addressUser)

userAddress

2021-03-09 19:02 UTC, Pavellys commented on .circleci/config.yml
> +      #          command: chmod 777 src/test/resources/webdrivers/linux/chromedriver
done

2021-03-09 19:03 UTC, Pavellys commented on src/test/java/tests/CartTest.java
> +        Assert.assertTrue(cartPage.isCheckInCart(PROMOTION_PRODUCT));
done

2021-03-09 19:09 UTC, Pavellys commented on src/main/java/pages/CartPage.java
> +        log.info("Entering data in address form 'Доставка по РБ'");
done

2021-03-10 15:48 UTC, Pavellys commented on pom.xml
> +                <version>3.8.0</version>
done

2021-03-10 15:51 UTC, merged