Fix master
Pavellys/MoiShopBY pull request #9
Opened 2021-03-17 19:51 UTC by Pavellys

2021-03-17 20:11 UTC, vchesnakoutest requested changes

2021-03-17 20:11 UTC, vchesnakoutest commented on src/test/java/tests_data/TestData.java
> +    static UserData userData = new UserData("Pavel", "3333856769");
static не советую, могут быть проблемы с многопоточностью

2021-03-17 20:31 UTC, Pavellys commented on src/test/java/tests_data/TestData.java
> +    static UserData userData = new UserData("Pavel", "3333856769");
done

2021-03-18 18:27 UTC, vchesnakoutest approved these changes
please merge

2021-03-18 19:54 UTC, merged